<?php
/**
 * Created by PhpStorm.
 * User: alexxorlovv
 * Date: 27.09.17
 * Time: 22:15
 */

namespace SweetKit\Foundation\Di\Tests;

use Sweetkit\Foundation\Di\Container;
use PHPUnit\Framework\TestCase;

class ContainerTest extends TestCase
{
    protected $di;
    function setUp()
    {
        $this->di = new Container();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    function testMy()
    {

    }

    function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
